[metadata]
name = germinate-diff
version = 1.0
description = Diff the expanded seed package lists between two refs
url = https://git.launchpad.net/germinate-diff
license = GNU GPL

[options]
packages = find:
python_requires = >=3.6
scripts =
    bin/germinate-diff

[options.packages.find]
exclude =
    tests

[flake8]
max-line-length = 79
ignore =
    # Incompatible with Black.
    E203,
    W503
