"""Tests for the retention check and its report."""

import os

from germidiff.listfile import Reason, parse_why
from germidiff.probe import ProbeResult, drop_alternative
from germidiff.report import format_probes, format_retained
from germidiff.retention import Retained, find_retained, soft_edges
from germidiff.runner import GerminateRun
from tests.helpers import TestCase


class TestParseWhy(TestCase):
    def test_seeded(self):
        reason = parse_why("Platform.Stonking build-essential seed")
        self.assertEqual(Reason.SEEDED, reason.kind)
        self.assertFalse(reason.soft)

    def test_recommends(self):
        reason = parse_why("dpkg-dev (Recommends)")
        self.assertEqual(Reason.RECOMMENDS, reason.kind)
        self.assertEqual("dpkg-dev", reason.holder)
        self.assertTrue(reason.soft)

    def test_depends(self):
        reason = parse_why("build-essential")
        self.assertEqual(Reason.DEPENDS, reason.kind)
        self.assertEqual("build-essential", reason.holder)
        self.assertFalse(reason.soft)

    def test_build_depends(self):
        reason = parse_why("linux (Build-Depend)")
        self.assertEqual(Reason.BUILD_DEPENDS, reason.kind)
        self.assertEqual("linux", reason.holder)
        self.assertFalse(reason.soft)

    def test_generated(self):
        self.assertEqual(Reason.OTHER, parse_why("Generated by gcc").kind)
        self.assertEqual(Reason.OTHER, parse_why("").kind)


class TestParseListFile(TestCase):
    def write_table(self, rows):
        body = "".join(
            "%-16s | %-8s | %-24s | x | 0 | 0\n" % (pkg, pkg, why)
            for pkg, why in rows
        )
        return self.write(
            os.path.join(self.make_temp_dir(), "desktop"),
            "Package          | Source   | Why                      | "
            "Maintainer | Deb Size (B) | Inst Size (KB)\n"
            "-----------------+----------+--------------------------+"
            "-----------+--------------+---------------\n"
            + body
            + "------------------------------------+-----+-----\n"
            "                                    |   0 |   0\n",
        )

    def test_reads_packages_and_reasons(self):
        from germidiff.listfile import parse_list_file

        path = self.write_table(
            [("vim", "Ubuntu desktop seed"), ("libgpm2", "vim")]
        )
        entries = parse_list_file(path)
        self.assertEqual({"vim", "libgpm2"}, set(entries))
        self.assertEqual(Reason.SEEDED, entries["vim"].kind)
        self.assertEqual("vim", entries["libgpm2"].holder)

    def test_header_rules_and_totals_are_not_packages(self):
        from germidiff.listfile import parse_list_file

        entries = parse_list_file(self.write_table([]))
        self.assertEqual({}, entries)

    def test_an_unreadable_file_is_empty_not_an_error(self):
        from germidiff.listfile import parse_list_file

        missing = os.path.join(self.make_temp_dir(), "nope")
        self.assertEqual({}, parse_list_file(missing))


class TestFindRetained(TestCase):
    def setUp(self):
        super().setUp()
        self.temp_dir = self.make_temp_dir()

    def write_run(self, side, seeds):
        """seeds: {name: [(pkg, why, explicit)]}"""
        out = os.path.join(self.temp_dir, side)
        os.makedirs(out, exist_ok=True)
        for name, rows in seeds.items():
            for suffix, wanted in (("", None), (".seed", True)):
                body = "".join(
                    "%-20s | %-10s | %-24s | x | 0 | 0\n" % (pkg, pkg, why)
                    for pkg, why, explicit in rows
                    if wanted is None or explicit
                )
                self.write(
                    os.path.join(out, name + suffix),
                    "Package | Source | Why | Maintainer | Deb | Inst\n"
                    "--------+--------+-----+------------+-----+-----\n"
                    + body
                    + "-----------------+-----+-----\n"
                    "                 |   0 |   0\n",
                )
        return out

    def make_run(self, seeds):
        packages = {
            name: {pkg for pkg, _, _ in rows} for name, rows in seeds.items()
        }
        return GerminateRun("new", "ref", list(seeds), packages)

    def test_package_held_only_by_a_recommends_is_flagged(self):
        old = self.write_run(
            "old", {"dev": [("build-essential", "Ubuntu dev seed", True)]}
        )
        new_seeds = {"dev": [("build-essential", "dpkg-dev (Recommends)",
                              False)]}
        new = self.write_run("new", new_seeds)

        retained = find_retained(old, new, self.make_run(new_seeds))
        self.assertEqual(1, len(retained))
        self.assertEqual("build-essential", retained[0].package)
        self.assertTrue(retained[0].soft)
        self.assertEqual(["dpkg-dev"], retained[0].holders)

    def test_package_held_by_a_hard_dependency_is_not_flagged_soft(self):
        old = self.write_run("old", {"dev": [("gcc", "Ubuntu dev seed",
                                              True)]})
        new_seeds = {"dev": [("gcc", "build-essential", False)]}
        new = self.write_run("new", new_seeds)

        retained = find_retained(old, new, self.make_run(new_seeds))
        self.assertEqual(1, len(retained))
        self.assertFalse(retained[0].soft)

    def test_a_hard_reason_in_any_seed_makes_it_not_soft(self):
        # Dropping a Recommends cannot remove a package another seed holds
        # through a real dependency.
        old = self.write_run("old", {"a": [("pkg", "Ubuntu a seed", True)],
                                     "b": []})
        new_seeds = {
            "a": [("pkg", "foo (Recommends)", False)],
            "b": [("pkg", "bar", False)],
        }
        new = self.write_run("new", new_seeds)

        retained = find_retained(old, new, self.make_run(new_seeds))
        self.assertFalse(retained[0].soft)

    def test_a_package_the_change_actually_removed_is_not_reported(self):
        # It shows up in the diff itself; there is nothing to explain.
        old = self.write_run("old", {"dev": [("gone", "Ubuntu dev seed",
                                              True)]})
        new_seeds = {"dev": []}
        new = self.write_run("new", new_seeds)

        self.assertEqual([], find_retained(old, new, self.make_run(new_seeds)))

    def test_nothing_reported_when_nothing_stopped_being_seeded(self):
        seeds = {"dev": [("gcc", "Ubuntu dev seed", True)]}
        old = self.write_run("old", seeds)
        new = self.write_run("new", seeds)
        self.assertEqual([], find_retained(old, new, self.make_run(seeds)))

    def test_soft_entries_are_reported_first(self):
        old = self.write_run(
            "old",
            {"dev": [("aaa", "Ubuntu dev seed", True),
                     ("zzz", "Ubuntu dev seed", True)]},
        )
        new_seeds = {
            "dev": [("aaa", "foo", False), ("zzz", "bar (Recommends)", False)]
        }
        new = self.write_run("new", new_seeds)

        retained = find_retained(old, new, self.make_run(new_seeds))
        self.assertEqual(["zzz", "aaa"], [r.package for r in retained])


class TestSoftEdges(TestCase):
    def test_collects_distinct_recommends_edges(self):
        retained = [
            Retained("be", [parse_why("dpkg-dev (Recommends)")], ["dev"]),
            Retained("gcc", [parse_why("build-essential")], ["dev"]),
        ]
        self.assertEqual([("dpkg-dev", "be")], soft_edges(retained))

    def test_deduplicates_one_holder_across_packages(self):
        retained = [
            Retained("a", [parse_why("h (Recommends)")], ["s"]),
            Retained("b", [parse_why("h (Recommends)")], ["s"]),
        ]
        self.assertEqual([("h", "a"), ("h", "b")], soft_edges(retained))


class TestDropAlternative(TestCase):
    def test_removes_a_whole_group(self):
        self.assertEqual(
            "gcc | c-compiler, fakeroot",
            drop_alternative("build-essential, gcc | c-compiler, fakeroot",
                             "build-essential"),
        )

    def test_keeps_the_other_alternatives(self):
        # Cutting "make | build-essential" down to nothing would also remove
        # make, which is a different question from the one being asked.
        self.assertEqual(
            "make", drop_alternative("make | build-essential",
                                     "build-essential")
        )

    def test_ignores_versions_and_arch_qualifiers(self):
        self.assertEqual(
            "c-compiler, foo:any",
            drop_alternative("gcc (>= 4:4.9) | c-compiler, foo:any", "gcc"),
        )
        self.assertEqual(
            "libc-dev",
            drop_alternative("libc6-dev [amd64] | libc-dev", "libc6-dev"),
        )

    def test_leaves_unrelated_fields_alone(self):
        self.assertEqual(
            "a, b | c", drop_alternative("a, b | c", "unrelated")
        )


class TestReportSections(TestCase):
    def test_retained_section_leads_with_the_soft_ones(self):
        retained = [
            Retained("build-essential", [parse_why("dpkg-dev (Recommends)")],
                     ["dev"]),
            Retained("gcc", [parse_why("build-essential")], ["dev"]),
        ]
        self.assertEqual(
            [
                "**no longer seeded, still pulled in**",
                "! build-essential: only by dpkg-dev (Recommends)",
                "  1 other held by hard dependencies: gcc",
            ],
            format_retained(retained),
        )

    def test_the_all_clear_does_not_read_like_the_warning(self):
        # Fixing the problem by seeding the package again must not leave a
        # report that differs only by a missing line.
        retained = [
            Retained("gcc", [parse_why("build-essential")], ["dev"]),
            Retained("make", [parse_why("dpkg-dev")], ["dev"]),
        ]
        lines = format_retained(retained)
        self.assertEqual(
            [
                "**no longer seeded, still pulled in**",
                "all 2 held by hard dependencies: gcc, make",
            ],
            lines,
        )
        self.assertNotIn("!", "\n".join(lines))

    def test_no_section_without_findings(self):
        self.assertEqual([], format_retained([]))
        self.assertEqual([], format_probes([]))

    def test_probe_section(self):
        probes = [ProbeResult("dpkg-dev", "build-essential",
                              ["g++", "build-essential"])]
        self.assertEqual(
            [
                "**retention probe**",
                "cutting dpkg-dev's Recommends of build-essential removes "
                "2 package(s):",
                "-build-essential",
                "-g++",
            ],
            format_probes(probes),
        )

    def test_probe_that_removes_nothing(self):
        probes = [ProbeResult("dpkg-dev", "build-essential", [])]
        self.assertIn("removes nothing", "\n".join(format_probes(probes)))

    def test_probe_error_is_reported_not_raised(self):
        probes = [ProbeResult("a", "b", error="boom")]
        self.assertIn("could not probe", "\n".join(format_probes(probes)))
