"""Reading germinate's table-formatted package lists.

The expanded lists germinate-diff diffs come from its JSON output, which is
the right thing to build on.  But germinate only records *why* a package is
in a list in its human-readable output -- ``write_full_list_json`` dumps
names alone -- so the retention check has to read the table format:

    Package         | Source | Why                    | Maintainer | ...
    ----------------+--------+------------------------+------------+----
    build-essential | ...    | dpkg-dev (Recommends)  | ...        | ...
    ----------------------------------------------+-----------------+---
                                                   |         1234567 | 89

Package names contain neither ``|`` nor whitespace, so splitting on ``|``
and dropping the header, rule and total rows is unambiguous.  Everything
here degrades to "no reason available" rather than raising, so a change to
germinate's output can cost the retention check but never the diff.
"""

__all__ = [
    "Reason",
    "parse_list_file",
    "parse_why",
]


class Reason:
    """A parsed germinate ``Why``.

    The forms come from the reason classes in ``germinate.germinator``:
    ``SeedReason`` renders as "<Branch> <name> seed", ``RecommendsReason`` as
    "<pkg> (Recommends)", ``BuildDependsReason`` as "<src> (Build-Depend)",
    ``DependsReason`` as a bare package name, and ``ExtraReason`` and
    ``RescueReason`` as "Generated by <src>" and "Rescued from <src>".
    """

    SEEDED = "seeded"
    DEPENDS = "depends"
    RECOMMENDS = "recommends"
    BUILD_DEPENDS = "build-depends"
    OTHER = "other"

    def __init__(self, text, kind, holder=None):
        self.text = text
        self.kind = kind
        #: The package that pulls this one in, where there is one.
        self.holder = holder

    @property
    def soft(self):
        """Whether this reason would vanish if a Recommends were dropped."""
        return self.kind == Reason.RECOMMENDS

    def __eq__(self, other):
        if not isinstance(other, Reason):
            return NotImplemented
        return (self.text, self.kind, self.holder) == (
            other.text,
            other.kind,
            other.holder,
        )

    def __hash__(self):
        return hash((self.text, self.kind, self.holder))

    def __repr__(self):  # pragma: no cover - debugging aid
        return "<Reason %r (%s)>" % (self.text, self.kind)


def parse_why(text):
    """Parse one ``Why`` string into a :class:`Reason`."""
    text = text.strip()
    if text.endswith(" (Recommends)"):
        return Reason(text, Reason.RECOMMENDS, text[: -len(" (Recommends)")])
    if text.endswith(" (Build-Depend)"):
        return Reason(
            text, Reason.BUILD_DEPENDS, text[: -len(" (Build-Depend)")]
        )
    if text.endswith(" seed"):
        return Reason(text, Reason.SEEDED)
    if text.startswith("Generated by ") or text.startswith("Rescued from "):
        return Reason(text, Reason.OTHER)
    if not text:
        return Reason(text, Reason.OTHER)
    return Reason(text, Reason.DEPENDS, text)


def _is_data_row(fields):
    if len(fields) < 3:
        return False
    name = fields[0]
    if not name or name == "Package":
        return False
    # Rules are drawn with dashes, and the totals row has no package name.
    if set(name) == {"-"}:
        return False
    return True


def parse_list_file(path):
    """Return ``{package: Reason}`` from one of germinate's list files.

    A file that cannot be read or parsed yields an empty mapping: the
    retention check is a convenience on top of the diff, never a reason for
    the whole run to fail.
    """
    entries = {}
    try:
        with open(path, encoding="UTF-8", errors="replace") as f:
            lines = f.readlines()
    except OSError:
        return entries

    for line in lines:
        fields = [field.strip() for field in line.split("|")]
        if not _is_data_row(fields):
            continue
        entries[fields[0]] = parse_why(fields[2])
    return entries
